# Generated by Django 4.2.7 on 2026-03-19 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='salary_bills/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('basic_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('da', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tds_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_metro', models.BooleanField(default=True)),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('regime', models.CharField(default='new', max_length=10)),
                ('gross_monthly', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('monthly_tds_required', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discrepancy', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax_status', models.CharField(blank=True, max_length=10)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_bills', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('manager_approved', 'Manager Approved'), ('finance_approved', 'Finance Approved'), ('rejected', 'Rejected'), ('settled', 'Settled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager_note', models.TextField(blank=True)),
                ('manager_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('finance_note', models.TextField(blank=True)),
                ('finance_actioned_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_claims', to=settings.AUTH_USER_MODEL)),
                ('salary_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='salary.salarybill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
